name: iTechSherpa
favicon: null
layout_spectrum: 0.50549
typography_spectrum: 0.949940888909623
title: 'AV, IT & more'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d7261c'
    - '#ea854b'
    - '#686868'
  brandStrength: 0.2534171927254647
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
